spring:
  datasource:
    url: jdbc:h2:mem:catalog_test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2