version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: admin_catalog_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog
    ports:
      - "5432:5432"
    networks:
        - admin_catalog_network

networks:
    admin_catalog_network:
